### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by hackerG7** [drudge/n8n-nodes-puppeteer#49]
I'm using portainer with self-built image of this repo.

Everything works but its always wait for so long until timeout when running any nodes

Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed. NodeOperationError: Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.     at ExecuteContext.handleError (/opt/n8n-custom-nodes/node_modules/n8n-nodes-puppeteer/nodes/Puppeteer/Puppeteer.node.ts:113:8)     at processItem (/opt/n8n-custom-nodes/node_modules/n8n-nodes-puppeteer/nodes/Puppeteer/Puppeteer.node.ts:589:24)     at runNextTicks (node:internal/process/task_queues:60:5)     at listOnTimeout (node:internal/timers:545:9)     at processTimers (node:internal/timers:519:7)     at async Promise.all (index 0)     at ExecuteContext.execute (/opt/n8n-custom-nodes/node_modules/n8n-nodes-puppeteer/nodes/Puppeteer/Puppeteer.node.ts:610:21)     at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:741:19)     at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:724:51     at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1155:20

**Comment by drudge** [comment]
Can you share some details of what you are running?

**Comment by Mo33aazz** [comment]
I'm experiencing the same issue. The loading takes a long time, followed by this error message: "Network.enable timed out. Increase the 'protocolTimeout' setting in launch/connect calls to set a higher timeout if necessary."

It worked perfectly on my local machine, but after switching to the Docker version and deploying it on Railway, I encountered this problem. @drudge

**Comment by Mo33aazz** [comment]
adding --disable-gpu to launch parameters in the node options fixed the problem

**Comment by ltb27** [comment]
> adding --disable-gpu to launch parameters in the node options fixed the problem


you saved me a lot of time, thank u so much.

**Comment by drudge** [comment]
You can also make sure Add Container Arguments is enabled.
